### ISSUE TITLE
Crashing with wrong number of arguments

### ISSUE THREAD

**Issue by brean** [brean/discord-bot-cud#7]
Don't crash with wrong number of arguments
''''
Traceback (most recent call last):
  File "/home/andreas/.local/share/virtualenvs/discord-bot-cud-bYWNHQIX/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/home/andreas/coding/cud/discord-bot-cud/discord_bot_cud/bot.py", line 274, in on_message
    await commands[txt_command](self, msg, *txt_params)
TypeError: cleanup() takes 1 positional argument but 2 were given
'''

**Comment by brean** [comment]
- use inspect to create list of parameter when setting up the bot
- The user should also define the parameter and some help-text so we can create a better .list_commands-command
